version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: g++ Sandbox/Sandbox.cpp -ICereal/Cereal -o bin/Sandbox -std=c++11
      - run: ./bin/Sandbox

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest