version: 2.0
jobs:
  build:
    docker:
      - image: gcc:latest
    working_directory: ~/cereal-build
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
        - run:
            name: Install CMake
            command: |
              apt-get -y -q update
              apt-get -y -q install cmake
        - checkout
        - run:
            name: Install Google Test
            command: |
              mkdir ~/googletest
              cd ~/googletest
              wget -qO - https://github.com/google/googletest/archive/release-1.8.0.tar.gz | tar -xz
              cmake -D CMAKE_INSTALL_PREFIX:PATH=$HOME/googletest -D CMAKE_BUILD_TYPE=Release googletest-release-1.8.0
              make install
        - run:
            name: Build Cereal
            command: |
              g++ Sandbox/Sandbox.cpp $HOME/googletest/lib/*.a -ICereal/Cereal -I $HOME/googletest/include/ -O2 -o test -pthread -std=c++11
        - run:
            name: Run unit tests
            command: |
              export GTEST_OUTPUT=xml:${TEST_RESULTS}/
              mkdir -p $TEST_RESULTS
              ./test
        - store_test_results:
            path: /tmp/test-results