version: 2.0
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: g++ Sandbox/Sandbox.cpp -ICereal/Cereal -o bin/Sandbox -std=c++11
      - run: ./bin/Sandbox